Polymorphism: Tests2 Class Reference
Tests2 Class Reference
#include <Tests2.h>
Public Member Functions
Tests2 ()
bool doTests ()
bool testCounting ()
bool testDoodlebugMove ()
bool testDoodlebugBreed ()
bool testDoodlebugStarve ()
bool testAntMove ()
bool testAntBreed ()
virtual ~Tests2 ()
Constructor & Destructor Documentation
Tests2()
Tests2::Tests2 ()
~Tests2()
Tests2::~Tests2 () virtual
Referenced by main().
Member Function Documentation
doTests()
bool Tests2::doTests ()
Carries out all the tests and makes sure that they all pass
Returns
true if all test pass, false if at least one fails.
References testAntBreed(), testAntMove(), testCounting(), testDoodlebugBreed(), testDoodlebugMove(), testDoodlebugStarve(), Grid::testFindEmptyCell(), Grid::testGetSetOccupant(), and Grid::testValidLocation().
Referenced by main().
testAntBreed()
bool Tests2::testAntBreed ()
Tests whether the ant breeds correctly or not
Returns
true if pass, false if fail
References ant, Ant::breed(), Cell::getOccupant(), Ant::move(), Cell::setPosition(), Ant::~Ant(), and Cell::~Cell().
Referenced by doTests().
testAntMove()
bool Tests2::testAntMove ()
Tests whether the ant moves into the cell it was told to move into
Returns
true if pass, false if fail
References ant, Cell::getCol(), Ant::getCol(), Cell::getOccupant(), Ant::getRow(), Cell::getRow(), Ant::move(), Cell::setPosition(), Ant::~Ant(), and Cell::~Cell().
Referenced by doTests().
testCounting()
bool Tests2::testCounting ()
Tests to make sure that getAntCount and getDoodleCount in Grid both work
Returns
true if pass, false if fail
References Grid::getAntCount(), Grid::getDoodleCount(), Grid::printGrid(), and Grid::~Grid().
Referenced by doTests().
testDoodlebugBreed()
bool Tests2::testDoodlebugBreed ()
Tests to make sure the doodlebug can breed and if it can't, won't.
Returns
true if pass, false if fail
References Doodlebug::breed(), doodlebug, Cell::getOccupant(), Doodlebug::move(), Cell::setPosition(), Cell::~Cell(), and Doodlebug::~Doodlebug().
Referenced by doTests().
testDoodlebugMove()
bool Tests2::testDoodlebugMove ()
Tests to make sure the doodlebug moves to the cell it is told to move to.
Returns
true if pass, false if fail
References doodlebug, Doodlebug::getCol(), Cell::getCol(), Cell::getOccupant(), Doodlebug::getRow(), Cell::getRow(), Doodlebug::move(), Cell::setPosition(), Cell::~Cell(), and Doodlebug::~Doodlebug().
Referenced by doTests().
testDoodlebugStarve()
bool Tests2::testDoodlebugStarve ()
Tests to make sure the doodlebug starve function returns the correct boolean.
Returns
true if pass, false if fail
References Doodlebug::move(), Cell::setPosition(), Doodlebug::starve(), Cell::~Cell(), and Doodlebug::~Doodlebug().
Referenced by doTests().
The documentation for this class was generated from the following files:
Tests2.h
Tests2.cpp