Polymorphism: Cell Class Reference
Cell Class Reference
#include <Cell.h>
Public Member Functions
Cell ()
void setPosition (int r, int c)
bool setOccupant (occupationStatus g)
occupationStatus getOccupant ()
Organism * getCellOwner ()
virtual ~Cell ()
void setOrganism (Organism *set)
int getRow ()
int getCol ()
Private Attributes
occupationStatus guest
Organism * guy
int row
int column
Detailed Description
The cell class contains the organism that is at the position in the grid, as well as the type of organism that is in it.
Constructor & Destructor Documentation
Cell()
Cell::Cell ()
Creates a new cell
References column, empty, guest, guy, and row.
~Cell()
Cell::~Cell () virtual
Destroys the instance of this cell.
Referenced by Tests2::testAntBreed(), Tests2::testAntMove(), Tests2::testDoodlebugBreed(), Tests2::testDoodlebugMove(), and Tests2::testDoodlebugStarve().
Member Function Documentation
getCellOwner()
Organism * Cell::getCellOwner ()
Returns a pointer to the organism that this cell represents.
Returns
the organism that resides in this cell
References guy.
Referenced by Doodlebug::breed(), Ant::breed(), and Grid::run().
getCol()
int Cell::getCol ()
Gets the column of this cell
Returns
the column
References column.
Referenced by Grid::run(), Tests2::testAntMove(), Tests2::testDoodlebugMove(), and Grid::testFindEmptyCell().
getOccupant()
occupationStatus Cell::getOccupant ()
Returns the occupation status of this cell
Returns
empty, ant, or doodlebug
References guest.
Referenced by Grid::getCellOccupant(), Doodlebug::move(), Ant::move(), Grid::printGrid(), Grid::run(), Tests2::testAntBreed(), Tests2::testAntMove(), Tests2::testDoodlebugBreed(), and Tests2::testDoodlebugMove().
getRow()
int Cell::getRow ()
Gets the row of this cell
Returns
the row
References row.
Referenced by Doodlebug::move(), Ant::move(), Grid::run(), Tests2::testAntMove(), Tests2::testDoodlebugMove(), and Grid::testFindEmptyCell().
setOccupant()
bool Cell::setOccupant (occupationStatus g)
Sets the occupant type of this cell Setting it to ant will create a new ant in the organism space Setting it to doodlebug will create a new doodlebug in the organism space Setting it to empty will get rid of the entity in the organism space
Parameters
g the occupation status that this cell will take on
Returns
true
References ant, column, doodlebug, empty, guest, guy, and row.
Referenced by Doodlebug::breed(), Ant::breed(), Doodlebug::move(), Ant::move(), Grid::run(), Grid::setCellOccupant(), and Grid::setUpGrid().
setOrganism()
void Cell::setOrganism (Organism * set)
Sets the organism of this cell to a certain organism
Parameters
set the organism to let live in this cell
References guy.
Referenced by Doodlebug::move(), and Ant::move().
setPosition()
void Cell::setPosition (int r, int c)
Sets the position of this cell to a certain row and column
Parameters
r the row of this cell
c the column of this cell
References column, and row.
Referenced by Grid::Grid(), Tests2::testAntBreed(), Tests2::testAntMove(), Tests2::testDoodlebugBreed(), Tests2::testDoodlebugMove(), and Tests2::testDoodlebugStarve().
Field Documentation
column
int Cell::column private
Referenced by Cell(), getCol(), setOccupant(), and setPosition().
guest
occupationStatus Cell::guest private
Referenced by Cell(), getOccupant(), and setOccupant().
guy
Organism* Cell::guy private
Referenced by Cell(), getCellOwner(), setOccupant(), and setOrganism().
row
int Cell::row private
Referenced by Cell(), getRow(), setOccupant(), and setPosition().
The documentation for this class was generated from the following files:
Cell.h
Cell.cpp