Polymorphism: Grid Class Reference
Grid Class Reference
#include <Grid.h>
Public Member Functions
Grid (int nSquaresOnASide=20, int doodlebugs=5, int ants=100, int g=1000, int seed=1, int pause=0)
virtual ~Grid ()
int run ()
int getAntCount ()
int getDoodleCount ()
void printGrid ()
Static Public Member Functions
static bool testFindEmptyCell ()
static bool testValidLocation ()
static bool testGetSetOccupant ()
Private Member Functions
void setUpGrid (int number, occupationStatus toSetUp)
Cell * findOpenCell (int r, int c, occupationStatus toLookFor)
bool isValidLocation (int r, int c)
bool setCellOccupant (int r, int c, occupationStatus g)
occupationStatus getCellOccupant (int r, int c)
Private Attributes
int sizeOfGrid
int gens
int doodleLeft
int antsLeft
bool pause
Cell ** myGridCells_ptr_array = nullptr
Detailed Description
The grid class contains the grid for the simulation, and handles running all of the calculations for the simulation as well.
Constructor & Destructor Documentation
Grid()
Grid::Grid (int nSquaresOnASide = 20, int doodlebugs = 5, int ants = 100, int g = 1000, int seed = 1, int stop = 0)
Constructs a new grid
Parameters
nSquaresOnASide the diameter of the board, default is 20
doodlebugs the number of doodlebugs on the board, default is 5
ants the number of ants on the board, default is 100
g the number of generations to run, default is 1000
seed the seed to use when randomly generating the board, default is 1
stop if nonzero, then the program waits for user input before running another generation. default is 0.
References ant, antsLeft, doodlebug, doodleLeft, gens, myGridCells_ptr_array, pause, Cell::setPosition(), setUpGrid(), and sizeOfGrid.
Referenced by testFindEmptyCell(), testGetSetOccupant(), and testValidLocation().
~Grid()
Grid::~Grid () virtual
Destroys this object.
Referenced by Production::runProduction(), Tests2::testCounting(), testFindEmptyCell(), testGetSetOccupant(), and testValidLocation().
Member Function Documentation
findOpenCell()
Cell * Grid::findOpenCell (int r, int c, occupationStatus toLookFor) private
Finds a cell either below, above, to the right, or to the left of the cell denoted by r,c. It is looking for the type of cell denoted by the occupation status.
Parameters
r the row of the cell to look around
c the column of the cell to look around
toLookFor the type of cell we are looking for, either an empty one, ant one, or a doodlebug one
Returns
a pointer to the cell that the function deems is an "open" cell based on the occupationStatus. If the function does not find a cell, it will return a nullptr.
References getCellOccupant(), isValidLocation(), and myGridCells_ptr_array.
Referenced by run(), and testFindEmptyCell().
getAntCount()
int Grid::getAntCount ()
Gets the current number of ants on the board
Returns
the amount of ants on the board
References antsLeft.
Referenced by Production::runProduction(), and Tests2::testCounting().
getCellOccupant()
occupationStatus Grid::getCellOccupant (int r, int c) private
Returns the cell occupant at the cell denoted by r,c
Parameters
r the row of the cell
c the column of the cell
Returns
the occupationStatus of that cell (either empty, ant, or doodlebug)
References Cell::getOccupant(), and myGridCells_ptr_array.
Referenced by findOpenCell(), and testGetSetOccupant().
getDoodleCount()
int Grid::getDoodleCount ()
Gets the current number of doodlebugs on the board
Returns
the amount of doodlebugs on the board
References doodleLeft.
Referenced by Production::runProduction(), and Tests2::testCounting().
isValidLocation()
bool Grid::isValidLocation (int r, int c) private
Checks to see if the row and column are valid locations on this grid
Parameters
r the row to check
c the column to check
Returns
true if it is a valid point (0 <= r,c < sizeOfGrid), false if not
References sizeOfGrid.
Referenced by findOpenCell(), setUpGrid(), and testValidLocation().
printGrid()
void Grid::printGrid ()
Prints the current state of the grid, with doodlebugs denoted as "x" and ants denoted as "o"
References ant, doodlebug, Cell::getOccupant(), myGridCells_ptr_array, and sizeOfGrid.
Referenced by run(), Production::runProduction(), Tests2::testCounting(), testFindEmptyCell(), and testGetSetOccupant().
run()
int Grid::run ()
Runs the grid for however many generations specified or until an end condition is met.
Returns
the number of generations ran
References ant, antsLeft, Organism::breed(), doodlebug, doodleLeft, empty, findOpenCell(), gens, Cell::getCellOwner(), Cell::getCol(), Cell::getOccupant(), Cell::getRow(), Organism::getStepRan(), Organism::move(), myGridCells_ptr_array, pause, printGrid(), Cell::setOccupant(), Organism::setStepRan(), sizeOfGrid, Doodlebug::starve(), and Organism::~Organism().
Referenced by Production::runProduction().
setCellOccupant()
bool Grid::setCellOccupant (int r, int c, occupationStatus g) private
Sets the occupant of the cell at r,c to be either an ant, doodlebug, or empty
Parameters
r the row in the cell array
c the column in the cell array
g the status to set that cell to
Returns
true if occupant set, false if fail
References myGridCells_ptr_array, and Cell::setOccupant().
Referenced by testFindEmptyCell(), and testGetSetOccupant().
setUpGrid()
void Grid::setUpGrid (int number, occupationStatus toSetUp) private
Sets up the grid with an amount of a certain occupationStatus in random locations.
Parameters
number the amount of entities to put on the grid
toSetUp the kind of entity to put on the grid (ant or doodlebug?)
References empty, isValidLocation(), myGridCells_ptr_array, Doodlebug::row, Cell::setOccupant(), and sizeOfGrid.
Referenced by Grid().
testFindEmptyCell()
static bool Grid::testFindEmptyCell () inline static
Function to test whether findEmptyCell works
Returns
true if findEmptyCell works, false if failed
References ant, empty, findOpenCell(), Cell::getCol(), Cell::getRow(), Grid(), printGrid(), setCellOccupant(), and ~Grid().
Referenced by Tests2::doTests().
testGetSetOccupant()
static bool Grid::testGetSetOccupant () inline static
Tests to make sure that getOccupant and setOccupant in Grid both work
Returns
true if pass, false if fail
References ant, doodlebug, empty, getCellOccupant(), Grid(), printGrid(), setCellOccupant(), and ~Grid().
Referenced by Tests2::doTests().
testValidLocation()
static bool Grid::testValidLocation () inline static
Function to test whether isValidLocation works
Returns
true if works, false if fail
References Grid(), isValidLocation(), and ~Grid().
Referenced by Tests2::doTests().
Field Documentation
antsLeft
int Grid::antsLeft private
Referenced by getAntCount(), Grid(), and run().
doodleLeft
int Grid::doodleLeft private
Referenced by getDoodleCount(), Grid(), and run().
gens
int Grid::gens private
Referenced by Grid(), and run().
myGridCells_ptr_array
Cell** Grid::myGridCells_ptr_array = nullptr private
Referenced by findOpenCell(), getCellOccupant(), Grid(), printGrid(), run(), setCellOccupant(), and setUpGrid().
pause
bool Grid::pause private
Referenced by Grid(), and run().
sizeOfGrid
int Grid::sizeOfGrid private
Referenced by Grid(), isValidLocation(), printGrid(), run(), and setUpGrid().
The documentation for this class was generated from the following files:
Grid.h
Grid.cpp