Polymorphism: Production Class Reference
Production Class Reference
#include <Production.h>
Public Member Functions
Production (int argc, char *argv[])
bool runProduction (int argc, char *argv[])
virtual ~Production ()
Private Attributes
int gridSize = 20
int doodle = 5
int ant = 100
int time_steps = 1000
int seed = 1
int pause = 0
Detailed Description
The production class runs the program as specified by the command line inputs
Constructor & Destructor Documentation
Production()
Production::Production (int argc, char * argv[])
Sets up the program using the command line arguments
Parameters
argc the number of arguments
argv[] the array of arguments given by the command line
References ant, doodle, gridSize, pause, seed, and time_steps.
Referenced by main().
~Production()
Production::~Production () virtual
Destroys the production instance.
Referenced by main().
Member Function Documentation
runProduction()
bool Production::runProduction (int argc, char * argv[])
Runs the program using the command line arguments
Parameters
argc the number of arguments
argv[] the array of arguments given by the command line
Returns
true if ran, false if failed
References ant, doodle, Grid::getAntCount(), Grid::getDoodleCount(), gridSize, pause, Grid::printGrid(), Grid::run(), seed, time_steps, and Grid::~Grid().
Referenced by main().
Field Documentation
ant
int Production::ant = 100 private
Referenced by Production(), and runProduction().
doodle
int Production::doodle = 5 private
Referenced by Production(), and runProduction().
gridSize
int Production::gridSize = 20 private
Referenced by Production(), and runProduction().
pause
int Production::pause = 0 private
Referenced by Production(), and runProduction().
seed
int Production::seed = 1 private
Referenced by Production(), and runProduction().
time_steps
int Production::time_steps = 1000 private
Referenced by Production(), and runProduction().
The documentation for this class was generated from the following files:
Production.h
Production.cpp