Polymorphism: Ant Class Reference
Ant Class Reference
#include <Ant.h>
Public Member Functions
Ant (int r=0, int c=0)
bool move (Cell *newCell)
bool breed (Cell *newCell)
int getRow ()
int getCol ()
~Ant ()
Public Member Functions inherited from Organism
Organism ()
virtual ~Organism ()
void setStepRan (bool b)
bool getStepRan ()
Private Attributes
int row = 0
int col = 0
Additional Inherited Members
Protected Attributes inherited from Organism
int timeStepsSurvived
bool stepRan
Detailed Description
The Ant class is a subclass of the Organism class, and is eligable to breed after it is alive for 3 timesteps, can be eaten by doodlebugs, and only moves into unoccupied cells.
Constructor & Destructor Documentation
Ant()
Ant::Ant (int r = 0, int c = 0)
Creates a new ant, which is also an organism
Parameters
r the row this ant resides in
c the column this ant resides in
References col, row, and Organism::timeStepsSurvived.
~Ant()
Ant::~Ant ()
Destroys the instance of the ant class
Referenced by Tests2::testAntBreed(), and Tests2::testAntMove().
Member Function Documentation
breed()
bool Ant::breed (Cell * newCell) virtual
Breeds a new ant into the cell denoted by newCell if the ant is eligable to breed.
Parameters
newCell the cell to breed into
Returns
true if bred, false if it didn't
Implements Organism.
References ant, empty, Cell::getCellOwner(), Cell::setOccupant(), Organism::setStepRan(), and Organism::timeStepsSurvived.
Referenced by Tests2::testAntBreed().
getCol()
int Ant::getCol () virtual
Gets the column that this ant resides in
Returns
the column
Implements Organism.
References col.
Referenced by move(), and Tests2::testAntMove().
getRow()
int Ant::getRow () virtual
Gets the row that this ant resides in
Returns
the row
Implements Organism.
References row.
Referenced by Tests2::testAntMove().
move()
bool Ant::move (Cell * newCell) virtual
Moves the ant to the cell specified NOTE: The user must remove this ant from its current cell ~before~ moving it to the new cell, as the ant itself does not keep track of what cell it is in, that is the grid's job
Parameters
newCell the new cell to put the ant in
Returns
true if move, false if fail
Implements Organism.
References ant, col, empty, getCol(), Cell::getOccupant(), Cell::getRow(), row, Cell::setOccupant(), Cell::setOrganism(), Organism::stepRan, and Organism::timeStepsSurvived.
Referenced by Tests2::testAntBreed(), and Tests2::testAntMove().
Field Documentation
col
int Ant::col = 0 private
Referenced by Ant(), getCol(), and move().
row
int Ant::row = 0 private
Referenced by Ant(), getRow(), and move().
The documentation for this class was generated from the following files:
Ant.h
Ant.cpp