Polymorphism: Organism Class Reference
Organism Class Reference abstract
#include <Organism.h>
Public Member Functions
Organism ()
virtual bool move (Cell *newCell)=0
virtual bool breed (Cell *newCell)=0
virtual int getRow ()=0
virtual int getCol ()=0
virtual ~Organism ()
void setStepRan (bool b)
bool getStepRan ()
Protected Attributes
int timeStepsSurvived
bool stepRan
Detailed Description
The organism class is a superclass for the Ant and Doodlebug class, and should never be instantiated as an actual object.
Constructor & Destructor Documentation
Organism()
Organism::Organism ()
Creates a new Organism
References stepRan, and timeStepsSurvived.
~Organism()
Organism::~Organism () virtual
Destroys the organism
Referenced by Grid::run().
Member Function Documentation
breed()
virtual bool Organism::breed (Cell * newCell) pure virtual
Implemented in Ant, and Doodlebug.
Referenced by Grid::run().
getCol()
virtual int Organism::getCol () pure virtual
Implemented in Ant, and Doodlebug.
getRow()
virtual int Organism::getRow () pure virtual
Implemented in Ant, and Doodlebug.
getStepRan()
bool Organism::getStepRan ()
Gets the stepRan boolean, which is a boolean that tells you whether this organism has been touched by the program in this generation
Returns
true if the program has touched this organism this generation, false otherwise
References stepRan.
Referenced by Grid::run().
move()
virtual bool Organism::move (Cell * newCell) pure virtual
Implemented in Ant, and Doodlebug.
Referenced by Grid::run().
setStepRan()
void Organism::setStepRan (bool b)
Sets the stepRan boolean, which is a boolean that tells you whether this organism has been touched by the program in this generation
Parameters
b the boolean to set it to
References stepRan.
Referenced by Doodlebug::breed(), Ant::breed(), and Grid::run().
Field Documentation
stepRan
bool Organism::stepRan protected
Referenced by getStepRan(), Doodlebug::move(), Ant::move(), Organism(), and setStepRan().
timeStepsSurvived
int Organism::timeStepsSurvived protected
Referenced by Ant::Ant(), Doodlebug::breed(), Ant::breed(), Doodlebug::Doodlebug(), Doodlebug::move(), Ant::move(), and Organism().
The documentation for this class was generated from the following files:
Organism.h
Organism.cpp