Polymorphism: Doodlebug Class Reference
Doodlebug Class Reference
#include <Doodlebug.h>
Public Member Functions
Doodlebug (int r, int c)
bool move (Cell *newCell)
bool breed (Cell *newCell)
bool starve ()
int getRow ()
int getCol ()
~Doodlebug ()
Public Member Functions inherited from Organism
Organism ()
virtual ~Organism ()
void setStepRan (bool b)
bool getStepRan ()
Private Attributes
int row
int column
int stepsWithoutEating = 0
Additional Inherited Members
Protected Attributes inherited from Organism
int timeStepsSurvived
bool stepRan
Detailed Description
The doodlebug class is a subclass of the Organism class, is eligable to breed after surviving 8 turns, can starve after not eating for 3 turns, can eat ants by moving into the cell that they are in, and will always move before the ants.
Constructor & Destructor Documentation
Doodlebug()
Doodlebug::Doodlebug (int r, int c)
Creates a new Doodlebug, which is also an Organism
Parameters
r the row that this doodlebug resides in
c the column that this doodlebug resides in
References column, row, and Organism::timeStepsSurvived.
~Doodlebug()
Doodlebug::~Doodlebug ()
Destroys the doodlebug instance.
Referenced by Tests2::testDoodlebugBreed(), Tests2::testDoodlebugMove(), and Tests2::testDoodlebugStarve().
Member Function Documentation
breed()
bool Doodlebug::breed (Cell * newCell) virtual
Breeds a new doodlebug into the cell denoted by newCell if the doodlebug is eligable to breed.
Parameters
newCell the cell to breed into
Returns
true if bred, false if it didn't
Implements Organism.
References doodlebug, empty, Cell::getCellOwner(), Cell::setOccupant(), Organism::setStepRan(), and Organism::timeStepsSurvived.
Referenced by Tests2::testDoodlebugBreed().
getCol()
int Doodlebug::getCol () virtual
Gets the column of the cell that this doodlebug resides in
Returns
the column
Implements Organism.
References column.
Referenced by move(), and Tests2::testDoodlebugMove().
getRow()
int Doodlebug::getRow () virtual
Gets the row of the cell that this doodlebug resides in
Returns
the row
Implements Organism.
References row.
Referenced by Tests2::testDoodlebugMove().
move()
bool Doodlebug::move (Cell * newCell) virtual
Moves the doodlebug to the cell specified NOTE: The user must remove this doodlebug from its current cell ~before~ moving it to the new cell, as the doodlebug itself does not keep track of what cell it is in, that is the grid's job
Parameters
newCell the new cell to put the doodlebug in
Returns
true, it will not fail to move.
Implements Organism.
References ant, column, doodlebug, getCol(), Cell::getOccupant(), Cell::getRow(), row, Cell::setOccupant(), Cell::setOrganism(), Organism::stepRan, stepsWithoutEating, and Organism::timeStepsSurvived.
Referenced by Tests2::testDoodlebugBreed(), Tests2::testDoodlebugMove(), and Tests2::testDoodlebugStarve().
starve()
bool Doodlebug::starve ()
Checks to see if the doodlebug starves NOTE: The user must deal with actually killing off the doodlebug, as this only checks to see if the doodlebug is eligable to starve.
Returns
true if the doodlebug will starve, false if it is fine
References stepsWithoutEating.
Referenced by Grid::run(), and Tests2::testDoodlebugStarve().
Field Documentation
column
int Doodlebug::column private
Referenced by Doodlebug(), getCol(), and move().
row
int Doodlebug::row private
Referenced by Doodlebug(), getRow(), move(), and Grid::setUpGrid().
stepsWithoutEating
int Doodlebug::stepsWithoutEating = 0 private
Referenced by move(), and starve().
The documentation for this class was generated from the following files:
Doodlebug.h
Doodlebug.cpp